version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: POSTGRESS_USER
      POSTGRES_PASSWORD: POSTGRESS_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  reverseproxy:
      image: borasmus/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: borasmus/udacity-c3-restapi-user
    env_file:
      - $HOME/.profile
    depends_on:
      - postgresql
  backend-feed:
    image: borasmus/udacity-c3-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - $HOME/.profile
    depends_on:
      - postgresql
  frontend:
    image: borasmus/udacity-c3-frontend:local
    ports:
      - "8100:80"
volumes:
  postgresql-data:
    driver: local

