version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: borasmus/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: borasmus/udacity-c3-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: borasmus/udacity-c3-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: borasmus/udacity-c3-frontend:v2
